version: '3'

services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - 5432:5432
